name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            friendlyName: Windows
    timeout-minutes: 10
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.17.0

      - name: Install and build dependencies
        run: yarn

      - name: Prettify
        run: yarn prettify

      - name: Lint
        run: yarn check-prettier

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Prebuild x64
        run: yarn prebuild-napi-x64

      - name: Prebuild arm64
        run: yarn prebuild-napi-arm64

      - name: Prebuild x86
        run: yarn prebuild-napi-ia32

      - name: Publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: yarn upload ${{ secrets.GITHUB_TOKEN }}
